# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-06 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='date',
            new_name='date_add',
        ),
        migrations.AddField(
            model_name='blog',
            name='active_from_date',
            field=models.DateField(auto_now=True, verbose_name='Дата активации'),
        ),
    ]
