# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-04 15:42
from __future__ import unicode_literals

from django.db import migrations, models
import www.models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0002_delete_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('date', models.DateField(auto_now=True, verbose_name='Дата')),
                ('desc', models.TextField(verbose_name='Текст новости')),
                ('active', models.BooleanField(default=True, verbose_name='Актовность')),
                ('img', models.ImageField(upload_to=www.models.dynamic_path, verbose_name='Картинка')),
            ],
        ),
    ]
