# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-08 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0004_auto_20170607_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='imported',
            field=models.BooleanField(default=False, verbose_name='Импортировать'),
        ),
    ]
