# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-11 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0005_auto_20170608_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='imported',
            field=models.BooleanField(default=False, verbose_name='Импорт'),
        ),
    ]
