# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 08:23
from __future__ import unicode_literals

from django.db import migrations
import sorl_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0007_auto_20170611_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='cropping',
            field=sorl_cropping.fields.ImageRatioField(blank=True, help_text=None, image_field='img', max_length=255, size='800x300'),
        ),
    ]
